- hosts: jenkins
  become: true
  tasks:
  - name: retrieving admin password for jenkins
    shell: |
      chmod 777 /var/lib/jenkins/secrets/initialAdminPassword    
      cat /var/lib/jenkins/secrets/initialAdminPassword
    register: shell_result
  - debug:
      var: shell_result.stdout_lines