version: '3.7'
services: 
  service1:
    build: 
      context: ./service1/
      dockerfile: Dockerfile.yaml
  service2: 
    build: 
      context: ./service2/
      dockerfile: Dockerfile.yaml
  service3:
    build: 
      context: ./service3/
      dockerfile: Dockerfile.yaml
  frontend:
    build: 
      context: .
      dockerfile: Dockerfile.yaml
  nginx:
    image: nginx:latest
    container_name: nginx
    ports: 
    - target: 80
      published: 80
      protocol: tcp
    volumes: 
    - type: bind
      source: ./nginx.conf
      target: /etc/nginx/nginx.conf
    depends_on: 
      - service1
        service2
        service3
        frontend


  
  
  
  
  
  
  
  
  
  
  

