version: '3.7'
services: 
  service1:
    image: dwarven-jenkins:5000/service1:service-${BUILD_NUMBER}
    build: 
      context: ./service1/
      dockerfile: Dockerfile
  service2:
    image: dwarven-jenkins:5000/service2:service-${BUILD_NUMBER}
    build: 
      context: ./service2/
      dockerfile: Dockerfile
  service3:
    image: dwarven-jenkins:5000/service3:service-{BUILD_NUMBER}
    build:
      context: ./service3/
      dockerfile: Dockerfile
  frontend:
    image: dwarven-jenkins:5000/frontend:service-${BUILD_NUMBER}
    build: 
      context: .
      dockerfile: Dockerfile
  nginx:
    image: nginx:latest
    ports: 
    - target: 80
      published: 80
      protocol: tcp
    volumes: 
    - type: bind
      source: ./nginx.conf
      target: /etc/nginx/nginx.conf
   


  
  
  
  
  
  
  
  
  
  
  

